// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Helpers;

namespace WebAPI.Migrations
{
    [DbContext(typeof(SqliteDataContext))]
    partial class SqliteDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("WebAPI.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Customer_Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebAPI.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("WebAPI.Entities.Mould", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartSet_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Moulds");
                });

            modelBuilder.Entity("WebAPI.Entities.Mould_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mould_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartMould_Type_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Part_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Mould_Details");
                });

            modelBuilder.Entity("WebAPI.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartSet_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkStation_Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("WebAPI.Entities.OperationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assigned_User")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Flow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Operation_Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operation_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OperationDetails");
                });

            modelBuilder.Entity("WebAPI.Entities.Operator_Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Entry_Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Entry_Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mould_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Operator_Entries");
                });

            modelBuilder.Entity("WebAPI.Entities.Operator_Entry_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created_Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Entry_Result")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Modified_Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operator_Entry_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Part_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Operator_Entry_Details");
                });

            modelBuilder.Entity("WebAPI.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Back_Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<int>("Customer_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hil_Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material_Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material_Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Part_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Part_No")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("WebAPI.Entities.PartMould_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mould_Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PartMould_Types");
                });

            modelBuilder.Entity("WebAPI.Entities.PartSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartSet_Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PartSets");
                });

            modelBuilder.Entity("WebAPI.Entities.PartSet_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartSet_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Part_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PartSet_Details");
                });

            modelBuilder.Entity("WebAPI.Entities.Production_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Production_Types");
                });

            modelBuilder.Entity("WebAPI.Entities.Schedule_Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Created_By")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date_Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date_Modified")
                        .HasColumnType("TEXT");

                    b.Property<int>("Machine_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Modified_By")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Part_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Required_Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Schedule_End_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Schedule_Start_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Schedule_Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("Shift_Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Schedule_Jobs");
                });

            modelBuilder.Entity("WebAPI.Entities.Shift_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Production_Type_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Shift_Types");
                });

            modelBuilder.Entity("WebAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAPI.Entities.WorkStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Machine_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkStations");
                });
#pragma warning restore 612, 618
        }
    }
}
